/**
 * Global application events only.
 *
 * Add events here only for cross-cutting infrastructure concerns shared across
 * multiple systems (session lifecycle, shared input intents, ownership
 * requests, voice plumbing, global notifications).
 *
 * If an event name starts to describe session-specific or item-specific gameplay
 * semantics, keep it inside the owning feature runtime and use
 * FeatureReplicationService for network fan-out instead of expanding the global bus.
 */
export const EVENTS = {
    START_XR: 'START_XR',
    JOIN_SESSION: 'JOIN_SESSION',
    CREATE_SESSION: 'CREATE_SESSION',
    HOST_READY: 'HOST_READY',
    SESSION_CONNECTED: 'SESSION_CONNECTED',
    ENTITY_DISCOVERED: 'ENTITY_DISCOVERED',
    PEER_DISCONNECTED: 'PEER_DISCONNECTED',
    ASSET_LOADED: 'ASSET_LOADED',
    ASSET_LOAD_ERROR: 'ASSET_LOAD_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    HOST_DISCONNECTED: 'HOST_DISCONNECTED',
    LOCAL_NAME_UPDATED: 'LOCAL_NAME_UPDATED',
    REMOTE_NAME_UPDATED: 'REMOTE_NAME_UPDATED',
    PEER_STATE_UPDATED: 'PEER_STATE_UPDATED',
    AVATAR_CONFIG_UPDATED: 'AVATAR_CONFIG_UPDATED',
    VOICE_STREAM_RECEIVED: 'VOICE_STREAM_RECEIVED',
    SCENE_READY: 'SCENE_READY',
    PHYSICS_READY: 'PHYSICS_READY',
    AUDIO_READY: 'AUDIO_READY',
    LOCAL_PLAYER_MOVED: 'LOCAL_PLAYER_MOVED',
    OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
    ENTITY_COLLIDED: 'ENTITY_COLLIDED',
    PHYSICS_COLLISION_STARTED: 'PHYSICS_COLLISION_STARTED',
    REQUEST_OWNERSHIP: 'REQUEST_OWNERSHIP',
    RELEASE_OWNERSHIP: 'RELEASE_OWNERSHIP',
    RECLAIM_OWNERSHIP: 'RECLAIM_OWNERSHIP',
    SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
    AUDIO_CHUNK_RECEIVED: 'AUDIO_CHUNK_RECEIVED',
    PEER_JOINED_SESSION: 'PEER_JOINED_SESSION',
    XR_SESSION_STARTED: 'XR_SESSION_STARTED',
    XR_SESSION_ENDED: 'XR_SESSION_ENDED',
    VOICE_STATE_UPDATED: 'VOICE_STATE_UPDATED',
    SOCIAL_HIGH_FIVE: 'SOCIAL_HIGH_FIVE',
    DESKTOP_SCREENS_UPDATED: 'DESKTOP_SCREENS_UPDATED',

    // Intents (Input -> Logic)
    INTENT_MOVE: 'INTENT_MOVE',
    INTENT_LOOK: 'INTENT_LOOK',
    INTENT_INTERACT_START: 'INTENT_INTERACT_START',
    INTENT_INTERACT_END: 'INTENT_INTERACT_END',
    INTENT_GRAB_START: 'INTENT_GRAB_START',
    INTENT_GRAB_END: 'INTENT_GRAB_END',
    INTENT_MENU_TOGGLE: 'INTENT_MENU_TOGGLE',
    INTENT_VR_SNAP_TURN: 'INTENT_VR_SNAP_TURN'
} as const;

export const PACKET_TYPES = {
    STATE_UPDATE: 0,
    PLAYER_INPUT: 1,
    PEER_DISCONNECT: 2,
    SESSION_CONFIG_UPDATE: 3,
    OWNERSHIP_REQUEST: 4,
    OWNERSHIP_RELEASE: 5,
    OWNERSHIP_TRANSFER: 6,
    AUDIO_CHUNK: 7,
    PEER_JOINED: 8,
    FEATURE_EVENT: 9,
    FEATURE_SNAPSHOT: 10,
    FEATURE_SNAPSHOT_REQUEST: 11,
    DESKTOP_SOURCES_STATUS_REQUEST: 12,
    DESKTOP_SOURCES_STATUS_RESPONSE: 13,
    DESKTOP_STREAM_SUMMON: 14,
    DESKTOP_STREAM_STOP: 15,
    DESKTOP_STREAM_SUMMONED: 16,
    DESKTOP_STREAM_STOPPED: 17,
    DESKTOP_STREAM_OFFLINE: 18,
    DESKTOP_STREAM_FRAME: 19,
    SESSION_NOTIFICATION: 20,
    RTT_PING: 21,
    RTT_PONG: 22,
    PEER_LATENCY_REPORT: 23,
    SCENARIO_ACTION_REQUEST: 24,
    SCENARIO_ACTION_EXECUTE: 25,
    SCENARIO_ACTION_RESULT: 26
} as const;

export const INPUT_CONFIG = {
    GAMEPAD_LOOK_SENSITIVITY: 1.5,
    MOBILE_LOOK_SENSITIVITY: 0.6,
    DEADZONE: 0.15,
    GESTURE: {
        PINCH_ON_DISTANCE: 0.035,   // meters
        PINCH_OFF_DISTANCE: 0.05,   // meters
        FIST_CURL_THRESHOLD: 0.095, // meters (tip-to-wrist)
        FIST_ON_CURL_COUNT: 3,
        FIST_OFF_CURL_COUNT: 1
    }
};
