export const EVENTS = {
    START_XR: 'START_XR',
    JOIN_ROOM: 'JOIN_ROOM',
    CREATE_ROOM: 'CREATE_ROOM',
    HOST_READY: 'HOST_READY',
    PEER_CONNECTED: 'PEER_CONNECTED',
    PEER_DISCONNECTED: 'PEER_DISCONNECTED',
    ASSET_LOADED: 'ASSET_LOADED',
    ASSET_LOAD_ERROR: 'ASSET_LOAD_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    HOST_DISCONNECTED: 'HOST_DISCONNECTED',
    LOCAL_NAME_UPDATED: 'LOCAL_NAME_UPDATED',
    REMOTE_NAME_UPDATED: 'REMOTE_NAME_UPDATED',
    AVATAR_CONFIG_UPDATED: 'AVATAR_CONFIG_UPDATED',
    VOICE_STREAM_RECEIVED: 'VOICE_STREAM_RECEIVED',
    SCENE_READY: 'SCENE_READY',
    PHYSICS_READY: 'PHYSICS_READY',
    AUDIO_READY: 'AUDIO_READY',
    LOCAL_PLAYER_MOVED: 'LOCAL_PLAYER_MOVED',
    OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
    ENTITY_COLLIDED: 'ENTITY_COLLIDED',
    REQUEST_OWNERSHIP: 'REQUEST_OWNERSHIP',
    RELEASE_OWNERSHIP: 'RELEASE_OWNERSHIP'
};

export const PACKET_TYPES = {
    STATE_UPDATE: 0,
    PLAYER_INPUT: 1,
    PEER_DISCONNECT: 2,
    ROOM_CONFIG_UPDATE: 3,
    OWNERSHIP_REQUEST: 4,
    OWNERSHIP_RELEASE: 5,
    OWNERSHIP_TRANSFER: 6
};

export const INPUT_CONFIG = {
    GAMEPAD_LOOK_SENSITIVITY: 1.5,
    MOBILE_LOOK_SENSITIVITY: 0.6,
    DEADZONE: 0.15
};
