export const EVENTS = {
    START_XR: 'START_XR',
    JOIN_ROOM: 'JOIN_ROOM',
    CREATE_ROOM: 'CREATE_ROOM',
    HOST_READY: 'HOST_READY',
    PEER_CONNECTED: 'PEER_CONNECTED',
    PEER_DISCONNECTED: 'PEER_DISCONNECTED',
    ASSET_LOADED: 'ASSET_LOADED',
    ASSET_LOAD_ERROR: 'ASSET_LOAD_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    HOST_DISCONNECTED: 'HOST_DISCONNECTED',
    LOCAL_NAME_UPDATED: 'LOCAL_NAME_UPDATED',
    REMOTE_NAME_UPDATED: 'REMOTE_NAME_UPDATED',
    PEER_STATE_UPDATED: 'PEER_STATE_UPDATED',
    AVATAR_CONFIG_UPDATED: 'AVATAR_CONFIG_UPDATED',
    VOICE_STREAM_RECEIVED: 'VOICE_STREAM_RECEIVED',
    SCENE_READY: 'SCENE_READY',
    PHYSICS_READY: 'PHYSICS_READY',
    AUDIO_READY: 'AUDIO_READY',
    LOCAL_PLAYER_MOVED: 'LOCAL_PLAYER_MOVED',
    OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
    ENTITY_COLLIDED: 'ENTITY_COLLIDED',
    DRUM_PAD_HIT: 'DRUM_PAD_HIT',
    PHYSICS_COLLISION_STARTED: 'PHYSICS_COLLISION_STARTED',
    REQUEST_OWNERSHIP: 'REQUEST_OWNERSHIP',
    RELEASE_OWNERSHIP: 'RELEASE_OWNERSHIP',
    RECLAIM_OWNERSHIP: 'RECLAIM_OWNERSHIP',
    SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
    PEN_DRAW_SEGMENT: 'PEN_DRAW_SEGMENT',
    AUDIO_CHUNK_RECEIVED: 'AUDIO_CHUNK_RECEIVED',
    PEER_JOINED_ROOM: 'PEER_JOINED_ROOM',
    XR_SESSION_STARTED: 'XR_SESSION_STARTED',
    XR_SESSION_ENDED: 'XR_SESSION_ENDED',
    VOICE_STATE_UPDATED: 'VOICE_STATE_UPDATED',

    // Intents (Input -> Logic)
    INTENT_MOVE: 'INTENT_MOVE',
    INTENT_LOOK: 'INTENT_LOOK',
    INTENT_INTERACT_START: 'INTENT_INTERACT_START',
    INTENT_INTERACT_END: 'INTENT_INTERACT_END',
    INTENT_GRAB_START: 'INTENT_GRAB_START',
    INTENT_GRAB_END: 'INTENT_GRAB_END',
    INTENT_VR_SNAP_TURN: 'INTENT_VR_SNAP_TURN'
};

export const PACKET_TYPES = {
    STATE_UPDATE: 0,
    PLAYER_INPUT: 1,
    PEER_DISCONNECT: 2,
    ROOM_CONFIG_UPDATE: 3,
    OWNERSHIP_REQUEST: 4,
    OWNERSHIP_RELEASE: 5,
    OWNERSHIP_TRANSFER: 6,
    DRAW_LINE_SEGMENT: 7,
    AUDIO_CHUNK: 8,
    PEER_JOINED: 9,
    FEATURE_EVENT: 10,
    FEATURE_SNAPSHOT: 11,
    FEATURE_SNAPSHOT_REQUEST: 12
} as const;

export const INPUT_CONFIG = {
    GAMEPAD_LOOK_SENSITIVITY: 1.5,
    MOBILE_LOOK_SENSITIVITY: 0.6,
    DEADZONE: 0.15,
    GESTURE: {
        PINCH_ON_DISTANCE: 0.035,   // meters
        PINCH_OFF_DISTANCE: 0.05,   // meters
        FIST_CURL_THRESHOLD: 0.095, // meters (tip-to-wrist)
        FIST_ON_CURL_COUNT: 3,
        FIST_OFF_CURL_COUNT: 1
    }
};
