import type { IAvatarConfig } from './GameState';
import type { IDrawSegmentPayload } from '../interfaces/IDrawing';
import type { IHandIntentPayload, ILookIntentPayload, IMoveIntentPayload, IVRSnapTurnPayload } from '../interfaces/IIntents';
import type { IVector3 } from '../interfaces/IMath';
import type { IVoiceStreamReceivedEvent } from '../interfaces/IVoice';

export interface AppEventMap {
    START_XR: void;
    JOIN_ROOM: string;
    CREATE_ROOM: string;
    HOST_READY: string;
    SESSION_CONNECTED: string;
    ENTITY_DISCOVERED: string;
    PEER_DISCONNECTED: string;
    ASSET_LOADED: unknown;
    ASSET_LOAD_ERROR: unknown;
    NETWORK_ERROR: string;
    HOST_DISCONNECTED: void;
    LOCAL_NAME_UPDATED: string;
    REMOTE_NAME_UPDATED: { peerId: string; name: string };
    PEER_STATE_UPDATED: string;
    AVATAR_CONFIG_UPDATED: IAvatarConfig;
    VOICE_STREAM_RECEIVED: IVoiceStreamReceivedEvent;
    SCENE_READY: void;
    PHYSICS_READY: void;
    AUDIO_READY: void;
    LOCAL_PLAYER_MOVED: unknown;
    OWNERSHIP_TRANSFERRED: unknown;
    ENTITY_COLLIDED: { intensity: number };
    DRUM_PAD_HIT: { padId: string; frequency: number; intensity: number; position?: IVector3 };
    PHYSICS_COLLISION_STARTED: { handleA: number; handleB: number; entityAId: string | null; entityBId: string | null };
    REQUEST_OWNERSHIP: unknown;
    RELEASE_OWNERSHIP: unknown;
    RECLAIM_OWNERSHIP: unknown;
    SYSTEM_NOTIFICATION: string;
    PEN_DRAW_SEGMENT: IDrawSegmentPayload;
    AUDIO_CHUNK_RECEIVED: unknown;
    PEER_JOINED_ROOM: string;
    XR_SESSION_STARTED: void;
    XR_SESSION_ENDED: void;
    VOICE_STATE_UPDATED: void;
    SOCIAL_HIGH_FIVE: { position?: IVector3; intensity: number };
    DESKTOP_SCREENS_UPDATED: void;
    INTENT_MOVE: IMoveIntentPayload;
    INTENT_LOOK: ILookIntentPayload;
    INTENT_INTERACT_START: IHandIntentPayload;
    INTENT_INTERACT_END: IHandIntentPayload;
    INTENT_GRAB_START: IHandIntentPayload;
    INTENT_GRAB_END: IHandIntentPayload;
    INTENT_VR_SNAP_TURN: IVRSnapTurnPayload;
}
